FROM locustio/locust:1.3.1

USER $USERNAME
# Use non-root user as a security measure
RUN groupadd -g 61000 docker
RUN useradd -g 61000 -l -m -s /bin/false -u 61000 docker

WORKDIR /tempcel
ADD locustfile.py .
EXPOSE 8089

ENTRYPOINT ["locust", "-f", "locustfile.py"]
#CMD ["--csv", "/tempcel/tempcel_1.0"]


