apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempcel-app
spec:
  replicas: 1 # Initial replica
  selector:
    matchLabels:
      app: tempcel
  template:
    metadata:
      labels:
        app: tempcel
    spec:
      containers:
      - name: tempcel
        image: kambla2662224/tempcel:latest
        port:
        - containerPort: 5000
      resources:
        # Resource requests and limits
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
