apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  replicas: 1 # Initial replica count (will be adjusted by HPA)
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: kambla5742224/locust:latest
        port:
        - containerPort: 8089
      resources:
        # Resource requests and limits (adjust as needed)
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi