apiVersion: v1
kind: Service
metadata:
  name: locust-svc
spec:
  selector:
    app: locust
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  type: NodePort  # Change to NodePort or ClusterIP or LoadBalancer if needed