name: Build and Push

on:
  push:
    branches: [main]

jobs:

  build-push-tempcel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile.tempcel --tag kambla2662224/tempcel:latest
      - name: Docker Push
        run: docker push kambla2662224/tempcel:latest

  build-push-locust:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: docker login
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER1_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER1_PASSWORD }}
              run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: Build the Docker image
              run: docker build . --file Dockerfile.locust --tag kambla5742224/locust:latest
            - name: Docker Push
              run: docker push kambla5742224/locust:latest
  